import { ScaledSheet } from "react-native-size-matters";

const emailConfirmationStyles = ScaledSheet.create({
  container: {
    backgroundColor: "#000",
    flex: 1,
    resizeMode: "contain",
    // paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  background: {
    // flex: 1,
    width: "100%",
    height: "800@s",
    alignItems: "center",
    marginTop: "-55@s",
  },
  box: {
    width: "275@s",
    height: "240@s",
    backgroundColor: "#1a1a1a",
    borderColor: "white",
    borderWidth: 0.5,
    alignItems: "center",
  },
  boxContainer: {
    // flex: 1,
    width: "80%",
    height: "auto",
    alignItems: "center",
  },
  buttonContainer: {
    flex: 0.4,
    marginTop: "50@s",
    overflow: "visible",
  },
  buttonStyle: {
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "black",
    borderColor: "white",
    borderWidth: "1@s",
    height: "30@s",
    width: "220@s",
    borderRadius: "4@s",
    // marginTop: "-120@s",
  },
  buttonText: {
    color: "white",
    fontSize: "15@s",
    // fontWeight: "600",
    letterSpacing: 2,
    fontFamily: "Helvetica-Bold",
  },
  congratsText: {
    width: "220@s",
    height: "63@s",
    alignItems: "center",
    marginTop: "15@s",
  },
  emailSignupContainer: {
    width: "100%",
    height: "50@s",
    alignItems: "center",
    justifyContent: "center",
    // backgroundColor: "red",
    marginTop: "25@s",
  },
  signupText: {
    width: "60%",
    color: "white",
    fontSize: "12@s",
    fontWeight: "500",
    textAlign: "center",
    letterSpacing: 1,
  },
  teamText: {
    color: "white",
    fontSize: "22@s",
    fontFamily: "Helvetica-Bold",
    marginTop: "10@s",
  },
  toTheText: {
    color: "white",
    fontSize: "17@s",
    marginTop: "10@s",
    fontFamily: "Helvetica",
  },
  welcomeTextContainer: {
    width: "100%",
    height: "auto",
    // backgroundColor: "red",
    marginTop: "20@s",
    alignItems: "center",
    justifyContent: "center",
  },
  welcomeText: {
    color: "white",
    fontSize: "45@s",
    fontFamily: "Helvetica-Bold",
  },
  whLogo: {
    width: "85%",
    height: "255@s",
    marginTop: "85@s",
    // marginRight: 5,
    overflow: "hidden",
  },
  whLogoContainer: {
    width: "100%",
    marginTop: "-80@s",
    marginRight: "15@s",
    // backgroundColor: "red",
    overflow: "hidden",
  },
  whLogoSmall: {
    width: "40%",
    height: "47@s",
    marginTop: "250@s",
  },
});

export default emailConfirmationStyles;
