module.exports = {
  Clips: require("./clips"),
  ConfirmAccount: require("./confirmAccount"),
  CreditCard: require("./creditCard"),
  Episodes: require("./episodes"),
  ForgotPassword: require("./forgotPassword"),
  GladiatorsLanding: require("./gladiatorsLanding"),
  HomePage: require("./homePage"),
  PlayVideoScreen: require("./playVideoScreen"),
  PlayClipsScreen: require("./playClipsScreen"),
  RentSeries: require("./rentSeries"),
  ResetPassword: require("./resetPassword"),
  SignIn: require("./signIn"),
  SignOut: require("./signOut"),
  SignUp: require("./signUp"),
  Store: require("./store"),
  UpcomingShows: require("./upcomingShows"),
  WaitList: require("./waitList"),
};
